-- 本地开发环境权限初始化脚本
-- 在 00-local-roles.sql 之后执行

-- 1. 授予 anon 角色所有表的访问权限
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;

-- 2. 禁用所有表的行级安全（RLS）- 仅用于本地开发
-- 注意：生产环境不应该禁用 RLS
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE games DISABLE ROW LEVEL SECURITY;
ALTER TABLE eavesdrop_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE intel_fragments DISABLE ROW LEVEL SECURITY;
ALTER TABLE intel_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE intel_intercepts DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE rumors DISABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE treasury DISABLE ROW LEVEL SECURITY;
ALTER TABLE steward_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE steward_stamina DISABLE ROW LEVEL SECURITY;
ALTER TABLE maid_relationships DISABLE ROW LEVEL SECURITY;
ALTER TABLE servant_relationships DISABLE ROW LEVEL SECURITY;
ALTER TABLE relationships DISABLE ROW LEVEL SECURITY;
ALTER TABLE action_approvals DISABLE ROW LEVEL SECURITY;
ALTER TABLE allowance_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE procurement_tickets DISABLE ROW LEVEL SECURITY;

-- 3. 授予 authenticated 角色相同权限（用于兼容）
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
